apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: greekgod659/voting-app-result:latest
        name: result
        ports:
        - containerPort: 80
          name: result
        env:
        # Environment variables for PostgreSQL connection
        - name: POSTGRES_HOST
          value: postgres  # The name of the PostgreSQL service
        - name: POSTGRES_PORT
          value: "5432"    # The default PostgreSQL port
        - name: POSTGRES_USER
          value: admin      # Your PostgreSQL user
        - name: POSTGRES_PASSWORD
          value: password  # Your PostgreSQL password
        - name: POSTGRES_DB
          value: voting_app # Your PostgreSQL database
