apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: greekgod659/voting-app-vote:latest
        name: vote
        ports:
        - containerPort: 80
          name: vote
        env:
        - name: REDIS_HOST
          value: redis  # The Kubernetes service name for Redis
        - name: REDIS_PORT
          value: "6379"  # Redis port
